### ISSUE TITLE
Grafana 4.0.1 issue

### ISSUE THREAD

**Issue by perbly** [dalmatinerdb/dalmatinerdb-datasource#18]
Hi

We are experiencing problems when running grafana 4.0.1 (3.1.1 works)

Reproduce:
1.Create graph or singlestat.
2. Select datasource - dalmatiner
3. Select from field, buckets are populated fine but when we select a bucket it's not being selected and the field only says "select collection"

Chrome and Firefox tested.

Chrome console error:

`TypeError: _.findWhere is not a function
    at eval (metric_segment.js:55)
    at o.$eval (boot.fdf40765.js:39)
    at o.$apply (boot.fdf40765.js:39)
    at o.$scope.updateVariableValue (metric_segment.js:54)
    at o.$scope.switchToLink (metric_segment.js:81)
    at b.$scope.updater (metric_segment.js:130)
    at b.select (boot.fdf40765.js:8)
    at b.click (boot.fdf40765.js:8)
    at HTMLUListElement.e (boot.fdf40765.js:34)
    at HTMLUListElement.dispatch (boot.fdf40765.js:35)`

Don't kill the messenger =)...

**Comment by Licenser** [comment]
hi perbly,
the change of the Grafana majour version (3 to 4) indicates that they break compatibility, the plugin is written for Grafana 3.

**Comment by perbly** [comment]
Bad of them. 

Do you have any indications on re-writing to support v4? i´m only asking to plan if we should release a grafana/dalmatiner platform on grafana 3 now or if we should wait a couple of weeks. We don´t actually see any hurry in grafana 4 but there are some cool new features that would be nice.

//Per

**Comment by Licenser** [comment]
I agree but they bump version numbers so at least it's obvious ;) I'd have wished that grafana 3 would be around longer so, it's always a pain to chase versions :(

Right now I've no immediate plan for grafana 4 but I don't know what code the concrete changes are either so it might be super simple but I'm a bit busy lately so I won't really have a chance to investigate that anytime soon.

**Comment by perbly** [comment]
Alright, thanks for responding. It looks like the datasource is working fine and this is probably some frontend issue. 
Closing the issue for now.
