### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by grinapo** [dalmatinerdb/dalmatinerdb-datasource#21]
I wanted to try the plugin. The documentation is scarce and hard to reproduce.

- The sentence "Install the plugin the grafana.net plugin page" doesn't quite compile in English. ;-)
- There seem to be no grafana.net page (grafana.com exists).
- Grafana.com doesn't contain anything with the substring "dalma".
- There ought to be some hints about manual install (I have to figure out anyway soon but...)

**Comment by grinapo** [comment]
also the documentation image says the connection is "proxy", while the real-life popup explanation say it's "direct".

**Comment by Licenser** [comment]
You have the great 'luck' to catch this repo right after submitted it to grafana.com ;) yesterday and changed the readme.

You can use both proxy and direct it depends on your network and configuration.

If you want to add a few words on how to manually install I'd be more then happy to include that in the readly!

**Comment by grinapo** [comment]
Manual install is dead simple: git clone it into the plugins directory as it is.

Oh okay, so direct works if I don't happen to block the access from the browser. :-)

But it doesn't, due to the different syntax: you use **http://host:8080/?q=SELECT** while dalmatiner fe expects **http://host:8080/?query=SELECT** .

Proxy works well indeed.

**Comment by Licenser** [comment]
nope the FE expects `?q=` `?query=` is just for the FE UI

**Comment by grinapo** [comment]
Manual install is dead simple: git clone it into the plugins directory as it is.

Oh okay, so direct works if I don't happen to block the access from the browser. :-)

But it doesn't, due to the different syntax: you use **http://host:8080/?q=SELECT** while dalmatiner fe expects **http://host:8080/?query=SELECT** .

Proxy works well indeed.

**Comment by grinapo** [comment]
Oh okay I have figured out. So yes, you're right it's "?q=" or rather "1.2.3.4:8080/?q=" and not **"1.2.3.4:8080//?q="**. That's pretty extremely stupid of FE, bailing out due to the extra slash. Which is there since good behaving netizens never forget the trailing slash. Except when it's not required (on data url), where it causes... this. 
So you may check for the extra slash (which shouldn't be there) or communicate to dalmatiner people not to choke on it.
Thanks for the help.

**Comment by Licenser** [comment]
I recommend improving your communication skills going around and insulting peoples work is not a very effective way to get them to help you.

**Comment by grinapo** [comment]
Would you care to show where have I insulted anyone? (Maybe it's been a self-advice?)

**Comment by grinapo** [comment]
(You haven't fixed the issue. The general expected behaviour is to inform the public at least why you reject to fix a problem or enhancement request.)

**Comment by Licenser** [comment]
The general expected behaviour is not to be rude to someone who give you free things, however you seem to choose to be. Releasing free software puts me at no obligation to deal with people who lack basic concepts of human interaction and act entitled, so yes I am free to chose not to.

It's a user error, no where is an extra / mentioned in the documentation or used in any place.

Anyway, please move along, don't use my software and leave me alone.
