### ISSUE TITLE
alias or modify legend format

### ISSUE THREAD

**Issue by sacreman** [dalmatinerdb/dalmatinerdb-datasource#5]
Currently the graph legend always displays the metric path query. It would be good to modify this so that it can show other things, most typically the host name.

I'd be happy to either use AS or ALIAS or the prometheus data source plugin exposes another field:

![alt text](http://trustmeiamadeveloper.com/content/images/2016/06/Screen-Shot-2016-06-27-at-15-37-35.png)

**Comment by starstuck** [comment]
We can add ALIAS keyword to grafana. To make it useful, we will need to have dalmatinerdb/dalmatinerdb#56 implemented.

**Comment by davecromberge** [comment]
this has been implemented as per https://github.com/dalmatinerdb/dalmatinerdb-datasource/pull/12, and dalmatinerdb/dalmatinerdb#56

**Comment by Licenser** [comment]
yay!
